apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    name: hello-world
  namespace: netology-homework
spec:
  containers:
  - name: hello-world
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
      - containerPort: 8080